[package]
name = "pulsar_rust_client"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
rmp-serde.workspace = true
bytes.workspace = true
log.workspace = true
uuid.workspace = true

pulsar_rust_net = { path = "../net" }
