[package]
name = "pulsar_rust_broker"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
rmp-serde.workspace = true
config.workspace = true
chrono.workspace = true
tokio.workspace = true
warp.workspace = true
ctrlc.workspace = true
hyper = { version = "*", features = ["http1", "server"] }
pulsar_rust_net = { path = "../net" }
