[package]
name = "pulsar-rust-broker"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
rmp-serde.workspace = true
config.workspace = true
chrono.workspace = true
hyper = { version = "*", features = ["http2", "server"] }
tokio.workspace = true
warp.workspace = true
